name: kafex
description: "Um guia confiável para quem ama café especial"
publish_to: 'none'
version: 3.0.1+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.0
  geolocator: ^9.0.2
  geocoding: ^2.1.1
  url_launcher: ^6.2.1
  cached_network_image: ^3.3.0
  flutter_rating_bar: ^4.0.1
  http: ^1.1.0
  google_fonts: ^6.3.1
  flutter_svg: ^2.2.1
  share_plus: ^7.2.2
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.4.10
  firebase_messaging: ^15.2.10  # Push Notifications
  firebase_analytics: ^11.3.3    # Analytics
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.2
  
  # Supabase
  supabase_flutter: 2.9.0
  supabase: 2.7.0
  
  # Imagens e Permissões
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  
  # UI
  phosphor_flutter: ^2.1.0
  flutter_local_notifications: ^17.0.0  # Notificações locais
  intl_phone_field: ^3.2.0  # Seletor de código de país com formatação
  mask_text_input_formatter: ^2.9.0  # Máscaras para campos de texto
  
  # Storage
  shared_preferences: ^2.2.3
  
  # App Updates
  upgrader: ^12.1.0
  package_info_plus: ^9.0.0
  
  # Arquitetura
  provider: ^6.1.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  
  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
  
  fonts:
    - family: Monigue
      fonts:
        - asset: assets/fonts/Monigue.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "app_icon/app-icon-kafex.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "app_icon/app-icon-kafex.png"
  windows:
    generate: true
    image_path: "app_icon/app-icon-kafex.png"
  macos:
    generate: true
    image_path: "app_icon/app-icon-kafex.png"

# Configuração da Splash Screen
flutter_native_splash:
  color: "#481009"
  image: assets/images/icon-kafex.png
  color_dark: "#481009"
  image_dark: assets/images/icon-kafex.png
  
  android_12:
    color: "#481009"
    image: assets/images/icon-kafex.png
    icon_background_color: "#481009"
  
  android: true
  ios: true
  web: true
  
  # Ícone pequeno e centralizado
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
  
  fullscreen: true