// lib/firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1p31nX0guUnaJH3W5a3Nk1ZeRmkpBnpg',
    appId: '1:1011389832396:web:4665de7a34adc391977669',
    messagingSenderId: '1011389832396',
    projectId: 'kafexapp',
    authDomain: 'kafexapp.firebaseapp.com',
    storageBucket: 'kafexapp.appspot.com',
    measurementId: 'G-28V0VLD67E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiWyJL4F1ccDvmC_ygJ2y64wSdLwk5TUA',
    appId: '1:1011389832396:android:bcd643f44214e8d9977669',
    messagingSenderId: '1011389832396',
    projectId: 'kafexapp',
    storageBucket: 'kafexapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvPNKGsVwykFzHyPCU0duD8nzpa3cTokA',
    appId: '1:1011389832396:ios:0c2481387b978196977669',
    messagingSenderId: '1011389832396',
    projectId: 'kafexapp',
    storageBucket: 'kafexapp.appspot.com',
    androidClientId: '1011389832396-2ifhcb0ot5fs8crtjjsqm1ue781etnag.apps.googleusercontent.com',
    iosClientId: '1011389832396-eevl9n172sab1th9k28dt9gqffdh7kh2.apps.googleusercontent.com',
    iosBundleId: 'com.lucasvieira.kafex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvPNKGsVwykFzHyPCU0duD8nzpa3cTokA',
    appId: '1:1011389832396:ios:130616f60c58453e977669',
    messagingSenderId: '1011389832396',
    projectId: 'kafexapp',
    storageBucket: 'kafexapp.appspot.com',
    androidClientId: '1011389832396-2ifhcb0ot5fs8crtjjsqm1ue781etnag.apps.googleusercontent.com',
    iosClientId: '1011389832396-d6rffuaajcbq6b2hvnd6slepp2atu5p0.apps.googleusercontent.com',
    iosBundleId: 'com.example.kafex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1p31nX0guUnaJH3W5a3Nk1ZeRmkpBnpg',
    appId: '1:1011389832396:web:4665de7a34adc391977669',
    messagingSenderId: '1011389832396',
    projectId: 'kafexapp',
    authDomain: 'kafexapp.firebaseapp.com',
    storageBucket: 'kafexapp.appspot.com',
    measurementId: 'G-28V0VLD67E',
  );

}