// lib/firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3s5D0-HxAGvqK9UlVfYeooYUsjbIZcJM',
    appId: '1:1011389832396:web:992448b7ebcfa5e0977669',
    messagingSenderId: '1011389832396',
    projectId: 'kafexapp',
    authDomain: 'kafexapp.firebaseapp.com',
    storageBucket: 'kafexapp.appspot.com',
    measurementId: 'G-X85SVED8XX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3s5D0-HxAGvqK9UlVfYeooYUsjbIZcJM',
    appId: '1:1011389832396:android:ANDROID_APP_ID', // Você precisa do app ID Android real
    messagingSenderId: '1011389832396',
    projectId: 'kafexapp',
    storageBucket: 'kafexapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3s5D0-HxAGvqK9UlVfYeooYUsjbIZcJM',
    appId: '1:1011389832396:ios:IOS_APP_ID', // Você precisa do app ID iOS real
    messagingSenderId: '1011389832396',
    projectId: 'kafexapp',
    storageBucket: 'kafexapp.appspot.com',
    iosClientId: 'IOS_CLIENT_ID', // Você precisa do client ID iOS real
    iosBundleId: 'com.kafex.app', // Ajuste conforme seu bundle ID
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3s5D0-HxAGvqK9UlVfYeooYUsjbIZcJM',
    appId: '1:1011389832396:ios:IOS_APP_ID', // Mesmo do iOS
    messagingSenderId: '1011389832396',
    projectId: 'kafexapp',
    storageBucket: 'kafexapp.appspot.com',
    iosClientId: 'IOS_CLIENT_ID',
    iosBundleId: 'com.kafex.app',
  );
}